## <i>Problem 12<i>
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

  1: 1
  3: 1,3
  6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?

In [1]:
def countf1(a): # количество делителей если порядковый номер треугольного числа четный
    b=2*a+1
    count=1
    counta=0
    countb=0
    for i in range(2,a+1):
        if a%i==0:
            counta+=1
    for j in range(2,b+1):
        if b%j==0:
            countb+=1
    return (count+counta+countb+counta*countb)# экспериментально найденное соотношение

def countf2(a):  # количество делителей если порядковый номер треугольного числа нечетный
    b=2*a-1
    count=1
    counta=0
    countb=0
    for i in range(2,a+1):
        if a%i==0:
            counta+=1
    for j in range(2,b+1):
        if b%j==0:
            countb+=1
    return (count+counta+countb+counta*countb)# экспериментально найденное соотношение
# для решения воспользуемся формулой по которой n-ое треугольное число вычисляется по формуле n*(n+1)/2
# тогда либо n, либо n+1 точно делится на 2, исходя из этого представляем 
# либо n = 2k , либо n+1 = 2k, далее производим расчет исходя из четности или нечетности n.
import time
n=1
k=0
count=1
start_time = time.time()
while count<500:
    if n%2==0:
        k=int(n/2)
        tnum=k*(2*k+1)
        count=countf1(k)
    else:
        k=int((n+1)/2)
        tnum=k*(2*k-1)
        count=countf2(k)
    n+=1
print(tnum,count, 'Время вычисления  ',time.time() - start_time)

76576500 576 Время вычисления   9.108999729156494

## <i>Problem 11<i>
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [11]:
# 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
# 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
# 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
# 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
# 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
# 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
# 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
# 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
# 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
# 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
# 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
# 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
# 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
# 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
# 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
# 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
# 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
# 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
# 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
# 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

In [5]:
import numpy as np
import time
start_time=time.time()
a='08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'
a=[int(s) for s in a.split()]
a=np.array(a)
a.resize(20,20)
maxqwe=0 # направление как на раскладке клавиатуры qwe
maxqaz=0 # направление qaz
maxqsc=0 # направление qsc
maxzse=0 # направление zse
for i in range(0,20):
    for j in range(0,16):    
        qwe=a[i][j]*a[i][j+1]*a[i][j+2]*a[i][j+3]
        if   qwe>maxqwe:
            maxqwe=qwe
for i in range(0,16):
    for j in range(0,20):           
        qaz=a[i][j]*a[i+1][j]*a[i+2][j]*a[i+3][j]
        if qaz>maxqaz:
            maxqaz=qaz
for i in range(0,16):
    for j in range(0,16):          
        qsc=a[i][j]*a[i+1][j+1]*a[i+2][j+2]*a[i+3][j+3]
        if qsc>maxqsc:
            maxqsc=qsc
for i in range(19,3,-1):
    for j in range(0,16):          
        zse=a[i][j]*a[i-1][j+1]*a[i-2][j+2]*a[i-3][j+3]
        if zse>maxzse:
            maxzse=zse            
print(max(maxqwe,maxqaz,maxqsc,maxzse),time.time()-start_time)

70600674 0.0010013580322265625

## <i>Problem 10<I>
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [3]:
import time
def sieve(n): # используем решето Эратосфена
    start_time = time.time()
    s = [True] * n
    s[0] = s[1] = False

    for i in range(2, int(n**(0.5))+1):
        if s[i]:
            for x in range(i*i, n, i):
                s[x] = False
    return sum([i for i in range(2,n) if s[i] == True]), "--- %s seconds ---" % (time.time() - start_time)

x,y = sieve(2000000)
print(x, y)

142913828922 --- 0.4510011672973633 seconds ---

In [4]:
import time # просто перебор с оптимизацией
start_time=time.time()
a=2000000
alls=[2]
id=1
for i in range(3,a+1,2): # убираем сразу все что делится на 2 и 5
    if i>10 and i%10==5:
            continue
    for j in alls: 
        if j*j-1 > i: # проверяем только j меньше корня из i согласно теории чисел
            alls.append(i)
            id+=1
            break
        if i%j==0:
            break
    else:
            alls.append(i)
            id+=1
print(sum(alls),time.time()-start_time)

142913828922 6.409029483795166

## <i>Problem 9<i>
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [6]:
import time
start_time=time.time()
num=1000
for a in range(1,1000):
    for b in range(a,1000):
        c=1000-a-b
        if a**2+b**2==c**2:
                print(a*b*c,time.time()-start_time)

31875000 0.13696742057800293

## <i>Problem 8<i>
The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.
Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [12]:

# 73167176531330624919225119674426574742355349194934
# 96983520312774506326239578318016984801869478851843
# 85861560789112949495459501737958331952853208805511
# 12540698747158523863050715693290963295227443043557
# 66896648950445244523161731856403098711121722383113
# 62229893423380308135336276614282806444486645238749
# 30358907296290491560440772390713810515859307960866
# 70172427121883998797908792274921901699720888093776
# 65727333001053367881220235421809751254540594752243
# 52584907711670556013604839586446706324415722155397
# 53697817977846174064955149290862569321978468622482
# 83972241375657056057490261407972968652414535100474
# 82166370484403199890008895243450658541227588666881
# 16427171479924442928230863465674813919123162824586
# 17866458359124566529476545682848912883142607690042
# 24219022671055626321111109370544217506941658960408
# 07198403850962455444362981230987879927244284909188
# 84580156166097919133875499200524063689912560717606
# 05886116467109405077541002256983155200055935729725
# 71636269561882670428252483600823257530420752963450

In [13]:
a=7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
import time
start_time=time.time()    
from functools import reduce
a=[int(x) for x in str(a)]
S=13
maxS=0
for i in range(len(a)+1-S):
    if reduce(lambda x,y: x*y, a[i:i+S])>maxS:
        maxS=reduce(lambda x,y: x*y, a[i:i+S])
print(maxS,time.time()-start_time)

23514624000 0.0019998550415039062

## <i>Problem 7<i>
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [15]:
a=100000
import time
start_time=time.time() 
list=[]
i=2
while len(list)<a:
    for j in range(2,int(i**0.5)+1):
        if i%j==0:
            i+=1
            break
    else:
        list.append(i)
        i+=1
print(list[-1],time.time()-start_time)

1299709 10.760021448135376

## <i>Problem 6<i>
The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)^2 = 55^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 
3025 - 385 = 2640    

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [17]:
a=100
# воспользуемся формулой суммы арифметической прогрессии
# для суммы чисел
sum=a*(a+1)/2
# для суммы квадратов 
sum_sq=(2*a+1)*(a+1)*a/6
print(sum**2-sum_sq)

25164150.0

## <i>Problem 5<i>
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [22]:
a =20
all=set()
for i in range(2,a+1):
    all.add(i)
notsimple=set()
for x in range(2,a+1):
    for j in range(2,a+1):
        if x%j==0 and x//j>1:
            notsimple.add(x)
simple=all-notsimple #определяем простые числа из диапазона
print('Простые числа в искомом ряду ',simple)
# путем анализа выявленно что искомое значение можно получить путем перемножения всех простых чисел в диапазоне, 
# а также дополнительным  умножением этих простых чисел возведенных в степень (у-1) по следующему правилу 
# х^у < а, где а - это наш заданный дипазон чисел, (у-1) -потому что один раз мы это простое число уже учли.
addnum=1
for i in simple:
    x=1
    y=1
    while y<a/(i**2): # здесь 2 потому что цикл всегда проскакивает одно значение, ну и учтем сразу что один раз мы уже учли простое число
        y=i**x 
        x+=1 
    addnum*=y
print(addnum)      
#Далее просто перемножаем наши простые числа и полученные дополнительные
answer=addnum
for x in simple:
    answer*=x 
print(answer)

Простые числа в искомом ряду  {2, 3, 5, 7, 11, 13, 17, 19}
24
232792560

## <i>Problem 4<i>
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [23]:
max=0
for i in range(100,1000):
    for j in range(100,1000):
        a=i*j 
        b=str(a)
        if  len(b)==6 and b[:3]==(b[5]+b[4]+b[3]):
            if a>max:
                max=a
print(max)

906609

## <i>Problem 3<i>
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [24]:
a=600851475143
i=2
while a>i:
    if a%i==0:
        a=a/i
    i+=1
print(a)

6857.0

## <i>Problem 2<i>
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [25]:
fib1=1
fib2=2
fib=0
sum=2
while fib<4000000:
    fib=fib1+fib2
    fib1,fib2=fib2,fib
    if fib%2==0:
        sum+=fib 
print(sum)

4613732

## <i>Problem 1<i>
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [26]:
sum=0
for i in range(3,1000,3):
    sum+=i
for j in range(5,1000,5):
    if j%3==0:
        continue
    else:
        sum+=j 
print(sum)

233168